apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerotohero
  labels:
    app: zerotohero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerotohero
  template:
    metadata:
      labels:
        app: zerotohero
    spec:
      containers:
      - image: "acraks02hero.azurecr.io/akszerotohero:v1"
        name: zerotohero-image
  
---

apiVersion: v1
kind: Service
metadata:
  name: zerotohero
spec:
  type: LoadBalancer
  selector:
    app: zerotohero 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80